config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
devise_for :stylists, controllers: {
  sessions:      'stylists/sessions',
  passwords:     'stylists/passwords',
  registrations: 'stylists/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
root 'users#top'
get 'posts/rank', to: 'posts#rank'
get 'users/top', to: 'users#top'
resources :users 
resources :stylists do
	resources :follows, only: [:create, :destroy, :show]
  resources :salons, expect: [:index]
end
resources :posts do
    resource :favorites, only: [:create, :destroy]
    resource :post_comments, only: [:create, :destroy]
end
resources :messages, only: [:create]
resources :rooms, only: [:create, :show, :index]
resources :user_chats, only: [:show, :create]
resources :chat_messages, only: [:create]
resources :boards do
	resource :board_comments, only: [:create, :destroy]
end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_chats, dependent: :destroy
  has_many :chat_messages, dependent: :destroy
  has_many :favorites
  has_many :posts, through: :favorites
  has_many :follows, dependent: :destroy
  has_many :stylists, through: :follows
  has_many :post_comments, dependent: :destroy


  attachment :user_image

  enum user_sex: { man: 1, woman: 2 }

  validates :user_name, presence: true, length: { in: 1..20 }
  validates :user_age, presence: true, length: { in: 1..20 }
  validates :email, presence: true, length: { in: 1..30 }
  validates :user_region,    length: { maximum: 20 }
  validates :user_hobby,    length: { maximum: 50 }
  validates :user_introduction,    length: { maximum: 500 }



end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      flash[:notice] = resource.errors.full_messages
      # respond_with resource
      redirect_to root_path
    end
  end


  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end

  def failed
    flash[:notice] = flash[:alert]
    redirect_to root_path
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
  protected

  def auth_options
    { scope: resource_name, recall: "#{controller_path}#failed" }
  end

end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :logged_in , only: [:show]
    before_action :authenticate_user!, :only => [:edit]


	def top

	end


	def show
		@user = User.find(params[:id])
		@chats = UserChat.where(user_id: @user.id)
		@favorites = Favorite.where("user_id = ?", @user)
		@follows = Follow.where("user_id = ?", @user)

	end

	def edit
		@user = User.find(params[:id])
	end



	def update
		@user = User.find(params[:id])
		@user.update(stylist_params)
		redirect_to user_path(current_user)
	end


	private

	def stylist_params
		params.require(:user).permit(:user_name, :user_sex, :user_age, :user_region, :user_hobby, :email,:user_introduction, :user_image)
	end


	def logged_in
        unless user_signed_in? || stylist_signed_in?
            redirect_to root_path
            
        end
        
    end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
  
     <h1 class="heads">edit</h1>

     <div class="editer">



      <%= form_for(@user) do |f| %>
                  <div>
                    <%= f.label :user_name %><br>
                    <%= f.text_field :user_name, class: "user_edit form-control" %>
                  </div>

                  
                  <div class="user_edit">
                    <%= f.label :user_sex %><br>
                    <%= f.label :man %>
                    <%= f.radio_button :user_sex, :man, class:"sex" %>
                    <%= f.label :woman %>
                    <%= f.radio_button :user_sex, :woman, class:"sex" %>
                  </div>

                  <div>
                    <%= f.label :user_age %><br>
                    <%= f.text_field :user_age, class: "user_edit form-control" %>
                  </div>

                  <div>
                    <%= f.label :user_region %><br>
                    <%= f.text_field :user_region, class: "user_edit form-control" %>
                  </div>

                  <div >
                    <%= f.label :user_hobby%><br>
                    <%= f.text_field :user_hobby, class: "user_edit form-control" %>
                  </div>

                  <div>
                    <%= f.label :email %><br>
                    <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"email user_edit form-control" %>
                  </div>

                  

                   <div>
                    <%= f.label :user_introduction%><br>
                    <%= f.text_area :user_introduction, class: "user_edit form-control" %>
                  </div>

                  <div>
                    <%= f.label :password %><br>
                    <% if @minimum_password_length %>
                    <em>(<%= @minimum_password_length %> characters minimum)</em>
                    <% end %>
                    <%= f.password_field :password, autocomplete: "new-password", class:"password user_edit form-control" %>
                  </div>

                  <div>
                    <%= f.label :password_confirmation %><br>
                    <%= f.password_field :password_confirmation, autocomplete: "new-password", class:"password_confirm user_edit form-control" %>
                  </div>
                  <div>
                  <div class="user-edit-image"><br>
                  <%= attachment_image_tag @user, :user_image, :fill, 200, 200,fallback: "/images/user_image.jpeg"%>
                  </div>
                  <label>ProfileImage</label>
                  <%= f.attachment_field :user_image, placeholder: "プロフィール画像", class: "edit-img" %>
                  </div>

                  <div>
                    <%= f.submit "Update", class: "btn btn-primary btn-lg ed" %>
                  </div>
      <% end %>
     
       



       
     </div>
</div>

app/views/users/show.html.erb
<div class="container ind">

    <div class="row">

      <div class="col-xs-12 col-lg-6 col-sm-6 profile-img">

            <div class="row">


                <%= attachment_image_tag @user, :user_image, :fill, 300, 300, format: 'jpeg', fallback: "/assets/user_image.jpeg", class: "stylist-pro" %> 



            </div>



            <div class="fallows row">
                
                          <div class="favorites">

                            
                             <p>follow <%= @user.follows.count%>    favorite <%= @user.favorites.count%></p>
                          </div>

          </div>

      </div>

      <div class="col-lg-6 col-sm-6 profile">
          <table class="table stylist-table">
            <tr><th class="stylist-table">名前</th><td><%= @user.user_name %></td></tr>
            <tr><th>性別</th><td><%= @user.user_sex %></td></tr>
            <tr><th>年齢</th><td><%= @user.user_age %> 歳</td></tr>
            <tr><th>住まい</th><td><%= @user.user_region %></td></tr>
            <tr><th>趣味</th><td><%= @user.user_hobby %></td></tr>
            <tr><th>自己紹介</th><td><%= @user.user_introduction %></td></tr>

        </table>

          
      </div>


    </div>


    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-6 talks">
      

          <% if current_user %>


            <button type="button" id="sampleButton2" class="btn btn-primary btn-lg">
            トーク
          </button>

          <!-- モーダル・ダイアログ -->
          <div class="modal fade" id="sampleModal2" tabindex="-1">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal"><span>×</span></button>
                  <h4 class="modal-title">TALK</h4>
                </div>
                <div class="modal-body">
                  <% @chats.each do |chat| %>
                  <table>
                    <tr>
                      <th class="col-xs-4"><%= link_to chat.stylist.stylist_name, stylist_path(chat), class: "stylist-name" %></th>
                      <td class="col-xs-4"><%= link_to 'TALK', user_chat_path(chat), class: "chat btn btn-primary btn-xs" %></td>

                    </tr>
                  </table>


                  <% end %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="chat btn btn-primary btn-xs" data-dismiss="modal">閉じる</button>
                </div>
              </div>
            </div>
          </div>

          <% end %>

          <%= link_to 'EDIT', edit_user_path(@user), class: "btn btn-primary btn-lg" %>
      </div>


      
    </div>


    <div class="row">

            <h2 class="styles">Favorite</h2>

            <div class="col-xs-12 col-sm-12 col-md-12">

              <% @user.posts.each do |post| %>
                    <div class="post">
                        <div class="blockarea">

                            <%= attachment_image_tag post, :post_image, :fill, 250, 250, format: 'jpeg' %>

                            <div class="caparea1">
                              <h3><%= post.post_name %></h3>
                              <h3><%= post.stylist.salon_name %></h3>
                              <p><%= link_to "SEE MORE", post_path(post.id) %></p>
                              <p>Favorit <%= post.favorites.count %>  View <%= post.impressionist_count %></p>


                            </div>
                        </div>
                    </div>
                <% end %>

              
            
            

            </div>
    
      </div>


      <div class="row">

            <h2 class="styles">Follow</h2>

           

              <% @user.stylists.each do |stylist| %>
              <table class="stylist-index">
              <th class="stylist-tab col-xs-2 col-md-2 col-lg-2"><%= attachment_image_tag stylist, :stylist_image, :fill, 100, 100, format: 'jpeg', fallback: "/images/stylist-fallback.jpeg" , class: "index-img" %><th>


              <td class="stylist-tab col-xs-2 col-md-2 col-lg-2"><%=link_to stylist.stylist_name , stylist_path(stylist), class: "stylist-name" %><hr class="under"></td>
              <td class="stylist-tab col-xs-2 col-md-2 col-lg-2"><%= stylist.salon_name %><hr class="under"></td>
              <td class="stylist-tab col-xs-2 col-md-2 col-lg-2"><%= stylist.stylist_region %><hr class="under"></td>
              <td class="stylist-tab col-xs-3 col-md-2 col-lg-2">Follow <%= stylist.follows.count %><hr class="under"></td>

            </table>
              <hr>
                <% end %>

              
            
            

          
    
      </div>








</div>

app/views/users/top.html.erb
<div class="top">

	<img src="/images/Collage_Fotors.jpg">


    <div class="errer"><%= flash[:notice] %></div>
	<div class="top-button sign_button sign_in_button"><p class="top-head1">USER</p></div>
	<div class="top-button2 sign_button sign_up_button"><p class="top-head1">STYLIST</p></div>
	
</div>



<div class="sign_modal_wrapper"></div>
<div class="sign_modal">
	<span class="fa_wrapper"><%= fa_icon "times" %></span>
			  <div class="sign_up_modal sign_modal_content">
			    <h2>STYLIST SIGN UP</h2>
					    <form class="new_stylist" id="new_stylist" action="/stylists" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="QFtz4Ocw6slu76jaDZVUcIVNwAgmTsG4jrHlUmsqryL3Lvn8KSnyvXr3KrOI3T5oi56FasvXMEodcEO7aN55xQ==" />
					  


					  <div class="field">
					    <label for="stylist_stylist_name">Stylist name</label><br />
					    <input autofocus="autofocus" type="text" name="stylist[stylist_name]" id="stylist_stylist_name" />
					  </div>

					  <div class="field">
					    <label for="stylist_salon_name">Salon name</label><br />
					    <input autofocus="autofocus" type="text" name="stylist[salon_name]" id="stylist_salon_name" />
					  </div>

					  <div class="field">
					    <label for="stylist_salon_name">Salon address</label><br />
					    <input autofocus="autofocus" type="text" name="stylist[address]" id="stylist_address" />
					  </div>

					  <div class="field">
					    <label for="stylist_stylist_age">Stylist age</label><br />
					    <input autofocus="autofocus" type="number" name="stylist[stylist_age]" id="stylist_stylist_age" />
					  </div>

					  <div class="field">
					    <label for="stylist_stylist_age">Stylist region</label><br />
					    <input autofocus="autofocus" type="text" name="stylist[stylist_region]" id="stylist_stylist_region" />
					  </div>



					  <div class="field">
					    <label for="stylist_email">Email</label><br />
					    <input autofocus="autofocus" autocomplete="email" type="email" value="" name="stylist[email]" id="stylist_email" />
					  </div>

					  <div class="field">
					    <label for="stylist_password">Password</label>
					    <em>(6 characters minimum)</em>
					    <br />
					    <input autocomplete="new-password" type="password" name="stylist[password]" id="stylist_password" />
					  </div>

					  <div class="field">
					    <label for="stylist_password_confirmation">Password confirmation</label><br />
					    <input autocomplete="new-password" type="password" name="stylist[password_confirmation]" id="stylist_password_confirmation" />
					  </div>

					  <div class="actions">
					    <input class="btn btn-primary btn-lg top-bt" type="submit" name="commit" value="Sign up" data-disable-with="Sign up" />
					  </div>
					</form>
			  </div>

			  <div class="sign_in_modal sign_modal_content">
			    <h2>USER SIGN UP</h2>



					    <form class="new_user" id="new_user" action="/users" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="r89udLJk9MhiQnlvyI1sQRSsBLk+Kah3gDOtM77mFo6AABFHKdGr4YPhxCJ2VyDtnmIGwfdL24gKq4Rw8FpQ/Q==" />
					  


						  <div class="field">
						    <label for="user_user_name">User name</label><br />
						    <input autofocus="autofocus" type="text" name="user[user_name]" id="user_user_name" />
						  </div>

						  <div class="field">
						    <label for="user_user_age">User age</label><br />
						    <input autofocus="autofocus" type="number" name="user[user_age]" id="user_user_age" />
						  </div>

						  <div class="field">
						    <label for="user_email">Email</label><br />
						    <input autofocus="autofocus" autocomplete="email" type="email" value="" name="user[email]" id="user_email" />
						  </div>

						  <div class="field">
						    <label for="user_password">Password</label>
						    <em>(6 characters minimum)</em>
						    <br />
						    <input autocomplete="new-password" type="password" name="user[password]" id="user_password" />
						  </div>

						  <div class="field">
						    <label for="user_password_confirmation">Password confirmation</label><br />
						    <input autocomplete="new-password" type="password" name="user[password_confirmation]" id="user_password_confirmation" />
						  </div>

						  <div class="actions">
						    <input class="btn btn-primary btn-lg top-bt" type="submit" name="commit" value="Sign up" data-disable-with="Sign up" />
						  </div>
						</form>


			  </div>
			</div>


<div class="sign_modal_wrapper2"></div>
<div class="sign_modal2">
   <span class="fa_wrapper2"><%= fa_icon "times" %></span>
             <div class="sign_up_modal2 sign_modal_content2">

              <h2>STYLIST's LOGIN</h2>
                        <form class="new_stylist" id="new_stylist" action="/stylists/sign_in"accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="9Gt52LDwSqdt9xtq/Wfr44PRre8I+kPlR8l9ma0QaYhbbojCcFbe1qSqDNio6fgiLeKMqx3ANIhxzKbDjg2xYQ==" />
						  <div class="field">
						    <label for="stylist_email">Email</label><br />
						    <input autofocus="autofocus" autocomplete="email" type="email" value="" name="stylist[email]" id="stylist_email" />
						  </div>

						  <div class="field">
						    <label for="stylist_password">Password</label><br />
						    <input autocomplete="current-password" type="password" name="stylist[password]" id="stylist_password" />
						  </div>

						    <div class="field">
						      <input name="stylist[remember_me]" type="hidden" value="0" /><input type="checkbox" value="1" name="stylist[remember_me]" id="stylist_remember_me" />
						      <label for="stylist_remember_me">Remember me</label>
						    </div>

						  <div class="actions">
						    <input class="btn btn-primary btn-lg top-bt" type="submit" name="commit" value="Log in" data-disable-with="Log in" />
						  </div>
						</form>

						<a class="tops" href="/stylists/password/new">Forgot your password?</a><br />



             </div>
             <div class="sign_in_modal2 sign_modal_content2">
              <h2>USER's LOGIN</h2>
                        <form class="new_user" id="new_user" action="/users/sign_in" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="N31SgXepRd54dXsZrmO0KASVYaiGEZ6kafnHif2vpa/RJNqRNkmSj8q6wR+Sddq3z9Im91AlgntRho/bXQIsqQ==" />
						  <div class="field">
						    <label for="user_email">Email</label><br />
						    <input autofocus="autofocus" autocomplete="email" type="email" value="" name="user[email]" id="user_email" />
						  </div>

						  <div class="field">
						    <label for="user_password">Password</label><br />
						    <input autocomplete="current-password" type="password" name="user[password]" id="user_password" />
						  </div>

						    <div class="field">
						      <input name="user[remember_me]" type="hidden" value="0" /><input type="checkbox" value="1" name="user[remember_me]" id="user_remember_me" />
						      <label for="user_remember_me">Remember me</label>
						    </div>

						  <div class="actions">
						    <input class="btn btn-primary btn-lg top-bt" type="submit" name="commit" value="Log in" data-disable-with="Log in" />
						  </div>
                        </form>


                        <a class="tops" href="/users/password/new">Forgot your password?</a><br />

             </div>
</div>
</div>