config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
devise_for :stylists, controllers: {
  sessions:      'stylists/sessions',
  passwords:     'stylists/passwords',
  registrations: 'stylists/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
root 'users#top'
get 'posts/rank', to: 'posts#rank'
get 'users/top', to: 'users#top'
resources :users 
resources :stylists do
	resources :follows, only: [:create, :destroy, :show]
  resources :salons, expect: [:index]
end
resources :posts do
    resource :favorites, only: [:create, :destroy]
    resource :post_comments, only: [:create, :destroy]
end
resources :messages, only: [:create]
resources :rooms, only: [:create, :show, :index]
resources :user_chats, only: [:show, :create]
resources :chat_messages, only: [:create]
resources :boards do
	resource :board_comments, only: [:create, :destroy]
end


end

app/models/stylist.rb
class Stylist < ApplicationRecord

  is_impressionable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :boards, dependent: :destroy
  
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries, dependent: :destroy

  has_many :user_chats, dependent: :destroy
  has_many :chat_messages, dependent: :destroy
  has_many :follows, dependent: :destroy
  has_many :user, through: :follows
  has_many :boards, dependent: :destroy
  has_many :board_comments, dependent: :destroy
  has_one :salon, dependent: :destroy

  attachment :stylist_image
  attachment :salon_image

  validates :stylist_name, presence: true, length: { in: 1..20 }
  validates :salon_name, presence: true, length: { in: 1..20 }
  validates :stylist_age, presence: true, length: { in: 1..20 }
  validates :email, presence: true, length: { in: 1..30 }
  validates :stylist_region,    length: { maximum: 20 }
  validates :stylist_hobby,    length: { maximum: 50 }
  validates :fort,    length: { maximum: 50 } 
  validates :stylist_introduction,    length: { maximum: 500 } 
  validates :phone_number,    length: { maximum: 15 } 
  validates :holiday,    length: { maximum: 30 } 
  validates :business_houre,    length: { maximum: 40 } 
  validates :menu,    length: { maximum: 500 } 
  validates :salon_introduction,    length: { maximum: 500 } 
  validates :salon_url,    length: { maximum: 100 } 










  

  enum stylist_sex: { man: 1, woman: 2 }

  def favorited_by?(user)
          follows.where(user_id: user.id).exists?
  end
end

app/controllers/stylists/confirmations_controller.rb
# frozen_string_literal: true

class Stylists::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/stylists/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Stylists::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/stylists/passwords_controller.rb
# frozen_string_literal: true

class Stylists::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/stylists/registrations_controller.rb
# frozen_string_literal: true

class Stylists::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    build_resource(sign_up_params)

    resource.save
    yield resource if block_given?
    if resource.persisted?
      if resource.active_for_authentication?
        set_flash_message! :notice, :signed_up
        sign_up(resource_name, resource)
        respond_with resource, location: after_sign_up_path_for(resource)
      else
        set_flash_message! :notice, :"signed_up_but_#{resource.inactive_message}"
        expire_data_after_sign_in!
        respond_with resource, location: after_inactive_sign_up_path_for(resource)
      end
    else
      clean_up_passwords resource
      set_minimum_password_length
      flash[:notice] = resource.errors.full_messages
      # respond_with resource
      redirect_to root_path
    end
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/stylists/sessions_controller.rb
# frozen_string_literal: true

class Stylists::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  def create
    self.resource = warden.authenticate!(auth_options)
    set_flash_message!(:notice, :signed_in)
    sign_in(resource_name, resource)
    yield resource if block_given?
    respond_with resource, location: after_sign_in_path_for(resource)
  end

  def failed
    flash[:notice] = flash[:alert]
    redirect_to root_path
  end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  protected

  def auth_options
    { scope: resource_name, recall: "#{controller_path}#failed" }
  end

end

app/controllers/stylists/unlocks_controller.rb
# frozen_string_literal: true

class Stylists::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/stylists_controller.rb
class StylistsController < ApplicationController
    before_action :logged_in , only: [:index, :show]
    before_action :authenticate_stylist!, :only => [:edit]

	impressionist only: [:show]

	def index
		@stylists = Stylist.all
		@rank = Stylist.find(Follow.group(:stylist_id).order('count(stylist_id) desc').limit(30).pluck(:stylist_id))

	end

	def show
		@stylist = Stylist.find(params[:id])
		@isRoom = false
		@room = Room.new
		@entry = Entry.new
		if current_stylist != nil
			@currentStylistEntry=Entry.where(stylist_id: current_stylist.id)
	        @stylistEntry=Entry.where(stylist_id: @stylist.id)
	     	@currentStylistEntry.each do |cu|
			        @stylistEntry.each do |u|
			            if cu.room_id == u.room_id
				            @isRoom = true
				            @roomId = cu.room_id
				            break
				         else
				           	@room = Room.new
				            @entry = Entry.new
				        end
			        end
				if @isRoom == true
					break
				end
	        end

	        if @isRoom == false
				@room = Room.new
				@entry = Entry.new
			end


	        @chats = UserChat.where(stylist_id: current_stylist.id)
	    else
	    	if UserChat.find_by(user_id: current_user.id, stylist_id: @stylist.id)
	    		@userChat = UserChat.find_by(user_id: current_user.id, stylist_id: @stylist.id)
	    	else
	         	@room = UserChat.new
	        end

	    end

	    @rooms = []
	    @stylist.entries.each do |entry|
	    	@rooms.push(entry.room)
	    end

	    @other = []
	    @rooms.each do |room|
	    	@other.push(room.stylists.where.not(id: @stylist.id)[0])
	    end

	    @post = Post.where(stylist_id: @stylist.id)



	    impressionist(@stylist, nil, unique: [:session_hash])







	end

	def edit
		@stylist = Stylist.find(params[:id])
	end



	def update
		@stylist = Stylist.find(params[:id])
		@stylist.update(stylist_params)
		redirect_to stylist_path(current_stylist)
	end


	private

	def stylist_params
		params.require(:stylist).permit(:stylist_name, :salon_name, :stylist_sex, :stylist_age, :stylist_region, :stylist_hobby, :email, :history, :stylist_introduction, :stylist_image, :post_code, :address, :phone_number, :holiday, :business_houre, :menu, :salon_image)
	end

	def logged_in
        unless user_signed_in? || stylist_signed_in?
            redirect_to root_path
            
        end
        
    end
end

app/helpers/stylists_helper.rb
module StylistsHelper
end

app/views/stylists/edit.html.erb
<div class="container">
  




      <h1 class="heads">EDIT</h1>

      <div class="row">
        


            <%= form_for(@stylist) do |f| %>

            <div class="col-xs-6 editer">
                       <h2>STYLIST</h2>

                          
                        <div>
                          <%= f.label :stylist_name %><br>
                          <%= f.text_field :stylist_name, class: "stylist_edit form-control"%>
                        </div>

                        

                        <div class="stylist_edit">
                          <%= f.label :stylist_sex %><br>
                          <%= f.label :man %>
                          <%= f.radio_button :stylist_sex, :man, class:"sex" %>
                          <%= f.label :woman %>
                          <%= f.radio_button :stylist_sex, :woman, class:"sex" %>
                        </div>

                        <div>
                          <%= f.label :stylist_age %><br>
                          <%= f.number_field :stylist_age, class: "stylist_edit form-control" %> 
                        </div>

                        <div>
                          <%= f.label :stylist_region %><br>
                          <%= f.text_field :stylist_region, class: "stylist_edit form-control" %>
                        </div>

                        <div >
                          <%= f.label :stylist_hobby%><br>
                          <%= f.text_field :stylist_hobby, class: "stylist_edit form-control" %>
                        </div>

                        <div>
                          <%= f.label :email %><br>
                          <%= f.email_field :email, autofocus: true, autocomplete: "email", class:"email stylist_edit form-control" %>
                        </div>

                        <div>
                          <%= f.label :history %><br>
                          <%= f.text_field :history, class: "stylist_edit form-control" %>年
                        </div>

                         <div>
                          <%= f.label :stylist_introduction%><br>
                          <%= f.text_area :stylist_introduction, class: "stylist_edit form-control" %>
                        </div>

                        <div>
                          <%= f.label :password %><br>
                          <% if @minimum_password_length %>
                          <em>(<%= @minimum_password_length %> characters minimum)</em>
                          <% end %>
                          <%= f.password_field :password, autocomplete: "new-password", class:"password stylist_edit form-control" %>
                        </div>

                        <div>
                          <%= f.label :password_confirmation %><br>
                          <%= f.password_field :password_confirmation, autocomplete: "new-password", class:"password_confirm stylist_edit form-control" %>
                        </div>
                        <div>
                        <div>
                        <%= attachment_image_tag @stylist, :stylist_image, :fill, 200, 200,fallback: "/images/user_image.jpeg"%>
                        </div>
                        <label>ProfileImage</label>
                        <%= f.attachment_field :stylist_image, placeholder: "プロフィール画像" ,class: "edit-img" %>
                        </div>
            </div>

            <div class="col-xs-6 editer">
                        <h2>SALON</h2>

                        
                        <div>
                          <%= f.label :salon_name %><br>
                          <%= f.text_field :salon_name, class: "stylist_edit form-control" %>
                        </div>
                        <div>
                          <%= f.label :address %><br>
                          
                          <%= f.text_field :address, class: "stylist_edit form-control" %>
                        </div>

                        <div>
                          <%= f.label :phone_number %><br>
                          <%= f.text_field :phone_number, class: "stylist_edit form-control" %>
                        </div>

                        <div>
                          <%= f.label :holiday %><br>
                          <%= f.text_field :holiday, class: "stylist_edit form-control"%>
                        </div>

                        <div >
                          <%= f.label :business_houre%><br>
                          <%= f.text_field :business_houre, class: "stylist_edit form-control" %>
                        </div>

                        <div>
                          <%= f.label :menu %><br>
                          <%= f.text_area :menu, class: "stylist_edit form-control" %>
                        </div>

                        <div>
                          <%= f.label :salon_introduction%><br>
                          <%= f.text_area :salon_introduction, class: "stylist_edit form-control" %>
                        </div>

                        <div>
                        <%= attachment_image_tag @stylist, :salon_image, :fill, 200, 200,fallback: "/images/user_image.jpeg"%>
                        </div>
                        <label>SalonImage</label>
                        <%= f.attachment_field :salon_image, placeholder: "salon画像", class: "edit-img" %>
            </div>
      </div>


      <div class="row editer ">

                        <div>
                          <%= f.submit "UPDATE", class: "btn btn-primary btn-lg" %>
                        </div>
      </div>
            <% end %>
      

</div>

app/views/stylists/index.html.erb
<div class="container">
	<div class="row">





		<h1 class="heads">STYLIST</h1>

		<!-- タブ・メニュー -->
				<ul class="nav nav-tabs tabs">
					<li  class="active"><a href="#sampleContentA" data-toggle="tab">ALL</a></li>
					<li><a href="#sampleContentB" data-toggle="tab">POP</a></li>
					
				</ul>

				<!-- タブ内容 -->
				<div class="tab-content">
					<div class="tab-pane active" id="sampleContentA">

						<% @stylists.each do |stylist| %>
						<table class="stylist-index">

						<th class="stylist-tab col-xs-2 col-md-2 col-lg-2"><%= attachment_image_tag stylist, :stylist_image, :fill, 100, 100, format: 'jpeg', fallback: "/images/stylist-fallback.jpeg", class: "index-img" %><th>


						  <td class="stylist-tab col-xs-2 col-md-2 col-lg-2"><%=link_to stylist.stylist_name , stylist_path(stylist), class: "stylist-name" %><hr class="under"></td>
						  <td class="stylist-tab col-xs-2 col-md-2 col-lg-2"><%= stylist.salon_name %><hr class="under"></td>
						  <td class="stylist-tab col-xs-2 col-md-2 col-lg-2"><%= stylist.stylist_region %><hr class="under"></td>
						  <td class="stylist-tab col-xs-2 col-md-2 col-lg-2">Follow <%= stylist.follows.count %><hr class="under"></td>

						</table>
						  <hr class="stylist-line">
						  <% end %>
					</div>
					<div class="tab-pane" id="sampleContentB">
						<% @rank.each.with_index(1) do |rank, i| %>
						<table class="stylist-index">
						<td class=" rank stylist-tab col-xs-2 col-md-2 col-lg-2"><%= "#{i}位" %></td>

						<td class="stylist-tab col-xs-2 col-md-2 col-lg-2"><%= attachment_image_tag rank, :stylist_image, :fill, 100, 100, format: 'jpeg', fallback: "/images/stylist-fallback.jpeg", class: "index-img"%><td>


						  <td class="stylist-tab col-xs-2 col-md-2 col-lg-2"><%=link_to rank.stylist_name , stylist_path(rank), class: "stylist-name" %><hr class="under"></td>
						  <td class="stylist-tab col-xs-2 col-md-2 col-lg-2"><%= rank.salon_name %><hr class="under"></td>
						  <td class="stylist-tab col-xs-2 col-md-2 col-lg-2"><%= rank.stylist_region %><hr class="under"></td>
						  <td class="stylist-tab col-xs-3 col-md-2 col-lg-2">Fallow　<%= rank.follows.count %><hr class="under"></td>

						</table>
						  <hr class="stylist-line">

						<% end %>
					</div>
					
				</div>

		<hr>

		
    </div>
</div>

app/views/stylists/show.html.erb
<div class="container ind">

  <div class="row">


        <div class="col-xs-12 col-lg-6 col-sm-6 profile-img">


          
          <div class="row">
              
              <%= attachment_image_tag @stylist, :stylist_image, :fill, 300, 300, format: 'jpeg', fallback: "/images/user_image.jpeg", class: "stylist-pro" %> 
          </div>
          

          <!-- ----------follow----------- -->
          <div class="fallows row">
                <% if current_user %>

                        <% if @stylist.favorited_by?(current_user) %>
                          <div class="favorites">
                            <%= link_to stylist_follow_path(@stylist), method: :delete do %>
                              <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                              follow
                          
                            <% end %>
                          </div>
                          

                        <% else %>
                          <div class="favorites">
                            <%= link_to stylist_follows_path(@stylist), method: :post do %>
                              <span class="glyphicon glyphicon-heart" aria-hidden="true"></span>
                              follow
                            <% end %>
                          </div>
                        <% end %>

                
                          
                <% end %>
                          <div class="favorites">

                            
                             <p>Follow <%= @stylist.follows.count %>   <string class="pv">View</string> <%= @stylist.impressionist_count %></p>
                          </div>

          </div>

          <!-- ----------follow----------- -->

          

        </div>

        <div class="col-lg-6 col-sm-6 profile">
          <table class="table stylist-table">
            <tr><th class="stylist-table">名前</th><td><%= @stylist.stylist_name %></td></tr>
          
            <tr><th>サロン</th><td><%= @stylist.salon_name %></td></tr>
            <tr><th>性別</th><td><%= @stylist.stylist_sex %></td></tr>
            <tr><th>年齢</th><td><%= @stylist.stylist_age %> 歳</td></tr>
            <tr><th>活動地域</th><td><%= @stylist.stylist_region %></td></tr>
            <tr><th>趣味</th><td><%= @stylist.stylist_hobby %></td></tr>
            <tr><th>スタイリスト歴</th><td><%= @stylist.history %> 年</td></tr>
            <tr><th>得意</th><td><%= @stylist.fort %></td></tr>
            <tr><th>自己紹介</th><td><%= @stylist.stylist_introduction %></td></tr>

        </table>

          
        </div>



  </div>


  <div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 talks">
        <div class="talk">
            <% if current_stylist != nil %>
              <% if current_stylist.id == @stylist.id %>
                    <button type="button" id="sampleButton" class="btn btn-primary btn-lg">TALK</button>

                  <!-- モーダル・ダイアログ -->
                  <div class="modal fade" id="sampleModal" tabindex="-1">
                    <div class="modal-dialog">
                      <div class="modal-content">
                        <div class="modal-header">
                          <button type="button" class="close" data-dismiss="modal"><span>×</span></button>
                          <h4 class="modal-title">TALK一覧</h4>
                        </div>
                        <div class="modal-body">
                          <% @chats.each do |chat| %>
                          <table>
                            <tr><th class="col-xs-4"><%=link_to chat.user.user_name , user_path(chat),class: "stylist-name" %></th>
                            <td class="col-xs-4"><%= link_to 'TALK', user_chat_path(chat), class: "chat btn btn-primary btn-xs" %></td></tr>
                          </table>
                          <% end %>

                          <% @other.each do |other| %>
                          <table>
                            <tr><th class="col-xs-4"><%= link_to other.stylist_name ,stylist_path(other), class: "stylist-name" %></th>
                            <td class="col-xs-4"><%= link_to 'TALK', room_path(@rooms), class: "chat btn btn-primary btn-xs" %></td></tr>

                          </table>

                          <% end %>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="btn-primary btn-lg" data-dismiss="modal">閉じる</button>
                        </div>
                      </div>
                    </div>
                  </div>
              <% end %>
            

            <% end %>
        </div>
        <div class="new-talk">

            <% if current_stylist != nil %>
                <% if @stylist.id != current_stylist.id %>

                  <% if @isRoom == true %>

                    <%= link_to 'TALK', room_path(@roomId),class: 'chat btn btn-primary btn-lg' %>

                  <% else %>
                      <%= form_for @room do |f| %>

                        <%= fields_for @entry do |e| %>
                          <%= e.hidden_field :stylist_id, :value=> @stylist.id %>
                        <% end %>
                      
                        <%= f.submit "TALK START", class: "chat btn btn-primary btn-lg" %>
                      <% end %>
                    
                  <% end %>

                <% end %>

              <% else %>
                <% if @userChat != nil %>
                  <%= link_to "TALK", user_chat_path(@userChat), class: "chat btn btn-primary btn-lg", method: :get %>
                <% else %>
                  <%= form_for @room do |f| %>
                    <%= f.hidden_field :stylist_id, :value=> @stylist.id %>
                    <%= f.submit "TALK START", class: "chat btn btn-primary btn-lg" %>
                  <% end %>
               <% end %>
              <% end %>
          </div>
          <div class="edit">
            <% if current_stylist != nil %>
              <% if current_stylist.id == @stylist.id %>

              <%= link_to 'EDIT', edit_stylist_path(@stylist), class: "btn btn-primary btn-lg" %>
              <% end %>
            <% end %>

          </div>
    </div>
  </div>

  <div class="row">

        <h2 class="styles">Style</h2>

        <div class="col-xs-12 col-sm-12 col-md-12">
        

            <% @post.each do |post| %>
                <div class="post">
                    <div class="blockarea">

                        <%= attachment_image_tag post, :post_image, :fill, 250, 250, format: 'jpeg' %>

                        <div class="caparea1">
                          <h3><%= post.post_name %></h3>
                          <h3><%= post.stylist.salon_name %></h3>
                          <p><%= link_to "SEE MORE", post_path(post.id) %></p>
                          <p>Favorit <%= post.favorites.count %>  View <%= post.impressionist_count %></p>


                        </div>
                    </div>
                </div>
            <% end %>

        </div>
    
  </div>
  <div class="row bottom">

         
           <%= link_to 'followers', stylist_follow_path(@stylist),class: "btn btn-primary btn-lg bottom-content" %>
           <%= link_to "stylist's salon", stylist_salon_path(@stylist), class: "btn btn-primary btn-lg" %>


  </div>





</div>