config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
devise_for :stylists, controllers: {
  sessions:      'stylists/sessions',
  passwords:     'stylists/passwords',
  registrations: 'stylists/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
root 'users#top'
get 'posts/rank', to: 'posts#rank'
get 'users/top', to: 'users#top'
resources :users 
resources :stylists do
	resources :follows, only: [:create, :destroy, :show]
  resources :salons, expect: [:index]
end
resources :posts do
    resource :favorites, only: [:create, :destroy]
    resource :post_comments, only: [:create, :destroy]
end
resources :messages, only: [:create]
resources :rooms, only: [:create, :show, :index]
resources :user_chats, only: [:show, :create]
resources :chat_messages, only: [:create]
resources :boards do
	resource :board_comments, only: [:create, :destroy]
end


end

app/models/board.rb
class Board < ApplicationRecord
	belongs_to :stylist
	has_many :board_comments, dependent: :destroy
	attachment :board_image


	validates :title, presence: true, length: { in: 1..30}
    validates :content, presence: true, length: { in: 1..200 }
    

end

app/models/board_comment.rb
class BoardComment < ApplicationRecord
	belongs_to :stylist
    belongs_to :board


    validates :comment, presence: true, length: { in: 1..500}
    
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :user_chat

   validates :content, presence: true, length: { in: 1..200 }
  
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :stylist
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
	belongs_to :user
    belongs_to :stylist
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :stylist
  belongs_to :room

   validates :content, presence: true, length: { in: 1..200 }
    
end

app/models/post.rb
class Post < ApplicationRecord
	is_impressionable counter_cache: true
	attachment :post_image

    belongs_to :stylist
    has_many :favorites
    has_many :users, through: :favorites
    has_many :post_comments, dependent: :destroy


    enum category: { men: 0, short: 1, medium: 2, long: 3 }


    validates :post_name, presence: true, length: { in: 1..20 }
    validates :post_opinion, presence: true, length: { in: 1..100 }
    
    


    def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
        end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	 belongs_to :user
     belongs_to :post

      validates :comment, presence: true, length: { in: 1..200 }
    



end

app/models/room.rb
class Room < ApplicationRecord

  has_many :messages, dependent: :destroy
  has_many :entries
  has_many :stylists, through: :entries
  # accepts_nested_attributes_for :entries
end

app/models/salon.rb
class Salon < ApplicationRecord
	belongs_to :order
end

app/models/stylist.rb
class Stylist < ApplicationRecord

  is_impressionable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :boards, dependent: :destroy
  
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries, dependent: :destroy

  has_many :user_chats, dependent: :destroy
  has_many :chat_messages, dependent: :destroy
  has_many :follows, dependent: :destroy
  has_many :user, through: :follows
  has_many :boards, dependent: :destroy
  has_many :board_comments, dependent: :destroy
  has_one :salon, dependent: :destroy

  attachment :stylist_image
  attachment :salon_image

  validates :stylist_name, presence: true, length: { in: 1..20 }
  validates :salon_name, presence: true, length: { in: 1..20 }
  validates :stylist_age, presence: true, length: { in: 1..20 }
  validates :email, presence: true, length: { in: 1..30 }
  validates :stylist_region,    length: { maximum: 20 }
  validates :stylist_hobby,    length: { maximum: 50 }
  validates :fort,    length: { maximum: 50 } 
  validates :stylist_introduction,    length: { maximum: 500 } 
  validates :phone_number,    length: { maximum: 15 } 
  validates :holiday,    length: { maximum: 30 } 
  validates :business_houre,    length: { maximum: 40 } 
  validates :menu,    length: { maximum: 500 } 
  validates :salon_introduction,    length: { maximum: 500 } 
  validates :salon_url,    length: { maximum: 100 } 










  

  enum stylist_sex: { man: 1, woman: 2 }

  def favorited_by?(user)
          follows.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_chats, dependent: :destroy
  has_many :chat_messages, dependent: :destroy
  has_many :favorites
  has_many :posts, through: :favorites
  has_many :follows, dependent: :destroy
  has_many :stylists, through: :follows
  has_many :post_comments, dependent: :destroy


  attachment :user_image

  enum user_sex: { man: 1, woman: 2 }

  validates :user_name, presence: true, length: { in: 1..20 }
  validates :user_age, presence: true, length: { in: 1..20 }
  validates :email, presence: true, length: { in: 1..30 }
  validates :user_region,    length: { maximum: 20 }
  validates :user_hobby,    length: { maximum: 50 }
  validates :user_introduction,    length: { maximum: 500 }



end

app/models/user_chat.rb
class UserChat < ApplicationRecord
  belongs_to :stylist
  belongs_to :user
  has_many :chat_messages, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	# before_action :authenticate_user!
	# before_action :authenticate_stylist!
    before_action :logged_in , only: [:index, :rank, :show]
    before_action :authenticate_stylist!, :only => [:create, :edit]
    impressionist only: [:show]




	def index
		@posts = Post.all
        @men = Post.where(category: 0 )
        @short = Post.where(category: 1)
        @medium = Post.where(category: 2 )
        @long = Post.where(category: 3 )

    end

    def rank
        @rank = Post.find(Favorite.group(:post_id).order('count(post_id) desc').limit(20).pluck(:post_id))
        @most_viewed = Post.order('impressions_count DESC').take(10)
    end

    def new
    	@post = Post.new
    end

    def show 
        @post = Post.find(params[:id])
        @post_comment = PostComment.new
        impressionist(@post, nil, unique: [:session_hash])

    end

    def create
        post = Post.new(post_params)
        post.stylist_id = current_stylist.id
        post.save
        redirect_to posts_path
    end

    def edit
        @post = Post.find(params[:id])
        


    end 

    def update
         @post = Post.find(params[:id])
         @post.update(post_params)
         redirect_to post_path(@post.id)
        
    end




    private
    def post_params
    params.require(:post).permit(:post_name, :post_opinion, :post_image, :stylist_id, :category)
    end

    def logged_in
        unless user_signed_in? || stylist_signed_in?
            redirect_to root_path
            
        end
        
    end

    




end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/salons_helper.rb
module SalonsHelper
end

app/helpers/stylists_helper.rb
module StylistsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/edit.html.erb
<div class="container">
  <h1 class="heads">EDIT</h1>

  <div class="edits">
    

        
        <%= form_for(@post) do |f| %>
         
          <h4 class="texter">タイトル</h4>
          <%= f.text_field :post_name, class: "form-control" %>
         
          <h4 class="texter">コメント</h4>
          <%= f.text_area :post_opinion, class: "form-control" %>

          <h4 class="texter">カテゴリー</h4>
          <%= f.select :category, Post.categories.keys.to_a, {}, class: "form-control" %>
         

         
         
          <h4 class="texter">イメージ</h4>
          <%= f.attachment_field :post_image , class: "img-post form-control" %>

          <div class="row sender">
         
          <%= f.submit '投稿', class: "btn btn-primary btn-lg top-bt top-new" %>

         </div>
         
        <% end %>
  

    
  </div>
  

</div>

app/views/posts/index.html.erb
<div class="ind container">

  <div class="row">

    







                   <h1 class="heads">SNAP</h1>

                   <% if current_stylist %>


                       <div class="row">
                         <p class="new_button news_button">NEW</p>


                       </div>
                   <% end %>


            

            <!-- タブ・メニュー -->
                    <ul class="nav nav-tabs tabs">
                          <li class="active "><a href="#sampleContentA" data-toggle="tab">ALL</a></li>
                          <li><a href="#sampleContentB" data-toggle="tab">MEN</a></li>
                          <li><a href="#sampleContentC" data-toggle="tab">SHORT</a></li>
                          <li><a href="#sampleContentD" data-toggle="tab">MEDIUM</a></li>
                          <li><a href="#sampleContentE" data-toggle="tab">LONG</a></li>

                    </ul>

                    <!-- タブ内容 -->
                    <div class="tab-content">

                      <div class="tab-pane active" id="sampleContentA">
                        <div class="test">

                            <% @posts.each do |post| %>
                                <div class="post">
                                   <div class="blockarea">

                                    <%= attachment_image_tag post, :post_image, :fill, 250, 250, format: 'jpeg' %>

                                   <div class="caparea1">
                                    <h3><%= post.post_name %></h3>
                                    <h3><%= post.stylist.salon_name %></h3>
                                     <p><%= link_to "SEE MORE", post_path(post.id) %></p>
                                     <p>Favorit <%= post.favorites.count %>  View <%= post.impressionist_count %></p>


                                   </div>
                                   </div>
                                </div>
                            <% end %>
                        </div>
                      </div>


                    <div class="tab-pane" id="sampleContentB">
                      <div class="test">
                        
                            <% @men.each do |post| %>
                                <div class="post">
                                    <div class="blockarea">

                                     <%= attachment_image_tag post, :post_image, :fill, 250, 250, format: 'jpeg' %>

                                    <div class="caparea1">
                                      <h3><%= post.post_name %></h3>
                                      <h3><%= post.stylist.salon_name %></h3>
                                      <p><%= link_to "SEE MORE", post_path(post.id) %></p>
                                     <p>Favorit <%= post.favorites.count %>  View <%= post.impressionist_count %></p>


                                    </div>
                                    </div>
                                </div>
                            <% end %>
                      </div>
                    </div>
                                  

                    <div class="tab-pane" id="sampleContentC">
                      <div class="test">
                            <% @short.each do |post| %>
                                <div class="post">
                                    <div class="blockarea">

                                      <%= attachment_image_tag post, :post_image, :fill, 250, 250, format: 'jpeg' %>

                                    <div class="caparea1">
                                      <h3><%= post.post_name %></h3>
                                      <h3><%= post.stylist.salon_name %></h3>
                                      <p><%= link_to "SEE MORE", post_path(post.id) %></p>
                                     <p>Favorit <%= post.favorites.count %>  View <%= post.impressionist_count %></p>


                                    </div>
                                    </div>
                                </div>
                            <% end %>
                      </div>
                    </div>

                    <div class="tab-pane" id="sampleContentD">
                      <div class="test">
                            <% @medium.each do |post| %>
                                <div class="post">
                                    <div class="blockarea">

                                      <%= attachment_image_tag post, :post_image, :fill, 250, 250, format: 'jpeg' %>

                                    <div class="caparea1">
                                      <h3><%= post.post_name %></h3>
                                      <h3><%= post.stylist.salon_name %></h3>
                                      <p><%= link_to "SEE MORE", post_path(post.id) %></p>
                                      <p>Favorit <%= post.favorites.count %>  View <%= post.impressionist_count %></p>


                                    </div>
                                    </div>
                                </div>
                           <% end %>
                      </div>
                    </div>

                    <div class="tab-pane" id="sampleContentE">
                      <div class="test">
                            <% @long.each do |post| %>
                                <div class="post">
                                    <div class="blockarea">

                                      <%= attachment_image_tag post, :post_image, :fill, 250, 250, format: 'jpeg' %>

                                    <div class="caparea1">
                                      <h3><%= post.post_name %></h3>
                                      <h3><%= post.stylist.salon_name %></h3>
                                      <p><%= link_to "SEE MORE", post_path(post.id) %></p>
                                      <p>Favorit <%= post.favorites.count %>  View <%= post.impressionist_count %></p>


                                    </div>
                                    </div>
                                </div>
                            <% end %>
                      </div>
                    </div>





                    </div>

  </div>
  

          



</div>



      <!-- モーダルー -->


      <div class="new_modal_wrapper"></div>
            <div class="new_modal">
              <span class="new_fa_wrapper"><%= fa_icon "times" %></span>
                  <div class="news_modal new_modal_content">
                    <h2 class="new-header">NEW</h2>
                          <form class="new_post" id="new_post" enctype="multipart/form-data" action="/posts" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="&#x2713;" /><input type="hidden" name="authenticity_token" value="lnDyIbUFVPqipqmEubjPH41D3cmsaFXB/ZCB0QDsJdMAQAnucZCZR1eADor2DdaZ3IjZYfSXi6HK4DFFWFKM7g==" />
                       
                                <h4>タイトル</h4>
                                  <input type="text" name="post[post_name]" id="post_post_name" />
                               
                                <h4>コメント</h4>
                                  <textarea name="post[post_opinion]" id="post_post_opinion"></textarea>

                                <h4>カテゴリー</h4>
                                  <select name="post[category]" id="post_category"><option value="men">men</option>
                                  <option value="short">short</option>
                                  <option value="medium">medium</option>
                                  <option value="long">long</option></select>
                               

                               
                               
                                <h4>イメージ</h4>
                                  <input value="{}" data-reference="4a1a04fa40500a1566b542f46d0e2b61" type="hidden" name="post[post_image]" /><input  class="img-post"  data-reference="4a1a04fa40500a1566b542f46d0e2b61" include_hidden="false" type="file" name="post[post_image]" id="post_post_image" />
                                 
                                  <input class="btn btn-primary btn-lg top-bt top-new" type="submit" name="commit" value="SEND" data-disable-with="SEND" />
                         
                      </form>
                  </div>
        
      </div>
        

app/views/posts/new.html.erb
<h1>新規投稿</h1>
<%= form_for(@post) do |f| %>
 
  <h4>タイトル</h4>
  <%= f.text_field :post_name %>
 
  <h4>本文</h4>
  <%= f.text_area :post_opinion %>

  <h4>カテゴリー</h4>
  <%= f.select :category, Post.categories.keys.to_a, {} %>
 

 
 
  <h4>画像</h4>
  <%= f.attachment_field :post_image %>
 
  <%= f.submit '投稿' %>
 
<% end %>

app/views/posts/rank.html.erb
<div class="container ind">

  <div class="row">
       <h2 class="heads">RANKING</h2>
  </div>

  <div class="row">
    <!-- タブ・メニュー -->
          <ul class="nav nav-tabs tabs">
            <li  class="active"><a href="#sampleContentA" data-toggle="tab">FAVORITE</a></li>
            <li><a href="#sampleContentB" data-toggle="tab">PV</a></li>
          </ul>

          <!-- タブ内容 -->
          <div class="tab-content">

              <div class="tab-pane  active" id="sampleContentA">
                <% @rank.each.with_index(1) do |rank, i| %>
                   <div class="post">
                        <p class="rank"><%= "#{i}位" %></p>
                      <div class="blockarea">
                        <%= attachment_image_tag rank, :post_image, :fill, 250, 250, format: 'jpeg' %>

                         <div class="caparea1">
                            <h3><%= rank.post_name %></h3>
                            <h3><%= rank.stylist.salon_name %></h3>
                            <p><%= link_to "SEE MORE", post_path(rank) %></p>
                            <p>Favorit <%= rank.favorites.count %>  View <%= rank.impressionist_count %></p>

                         </div>
                      </div>
                   </div>

                <% end %>
              </div>

              <div class="tab-pane" id="sampleContentB">
                <% @most_viewed.each.with_index(1) do |rank, i| %>
      
                  <div class="post">
                        <p class="rank"><%= "#{i}位" %></p>
                      <div class="blockarea">
                        <%= attachment_image_tag rank, :post_image, :fill, 250, 250, format: 'jpeg' %>

                         <div class="caparea1">
                            <h3><%= rank.post_name %></h3>
                            <h3><%= rank.stylist.salon_name %></h3>
                            <p><%= link_to "SEE MORE", post_path(rank) %></p>
                            <p>Favorit <%= rank.favorites.count %>  View <%= rank.impressionist_count %></p>

                         </div>
                      </div>
                   </div>
                  
                
                <% end %>
              </div>
            
          </div>


      
      
      
  
    

    
  </div>
  
  
</div>

app/views/posts/show.html.erb
<div class="container ind">

        <div class="row">

              <div class="col-xs-12 col-ld-6 col-md-6 show-img">
                
                 <div class="post-show"><%= attachment_image_tag @post, :post_image, :fill, 500, 500, format: 'jpeg', fallback: "/images/ooo.jpeg" %></div>
              </div>

          <div class="col-ld-6 col-md-6 shows">
            


                  <div class="row">


                      <div class="show-name"><%= attachment_image_tag @post.stylist, :stylist_image, :fill, 130, 130, format: 'jpeg', fallback: "/images/post_image.jpeg" , class: "stylist-image" %>

                      <%= @post.stylist.salon_name %>
                      <%= @post.stylist.stylist_name %></div>
                  
                    
                  

                  </div>

                  <div class="row show-favorite">

                      <% if current_user %>

                           <% if @post.favorited_by?(current_user ) %>

                              <p><%= link_to post_favorites_path(@post), method: :delete do %>
                                <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                                favorite</p>
                              <% end %>

                              <div>favorite <%= @post.favorites.count %></div>

                          <% else %>

                              <p><%= link_to post_favorites_path(@post), method: :post do %>
                                <i class="fa fa-heart-o" aria-hidden="true"></i>
                                favorite</p>
                              <% end %>

                              <div class="favorite-term">favorite <%= @post.favorites.count %></div>


                          <% end %>

                      <% else %>
                          <div class="favorite-term">favorite <%= @post.favorites.count %></div>

                      <% end %>
          


                      <div class="favorite-term"><string>View</string>
                      <%= @post.impressionist_count %></div>
                      <p>コメント <%= @post.post_comments.count %>件</p>



                  </div>

                  <div class="row show-contents">


                      <P class="show-title"><%= @post.post_name %></P>

                      <p class="show-opinion"><%= @post.post_opinion %></p>
                      
          
                      

                  </div>
           

            </div>
          
            
        </div>






        <div class="row show-coments ">
          <% if current_user %>
                  <% @post.post_comments.each do |post_comment| %>
                  <table>

                    <div class="show-coment">
                      <tr>
                      <th><%= attachment_image_tag post_comment.user, :user_image, :fill, 50, 50, format: 'jpeg', fallback: "/images/ooo.jpeg" , class: "stylist-image" %></th>
                
                                <td><%= post_comment.user.user_name %>
                                
                                <%= post_comment.created_at.strftime('%Y/%m/%d') %></td>
                            
                            
                                <td class="show-coment-dtail"><%= post_comment.comment %></td></tr>
                    </div>

                  </table>

                  <% end %>

                 


                  <%= form_for [@post, @post_comment] do |f| %>
                
                
                    <%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメント" %>
          
                  
                   <%= f.submit "送信する", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
                  <% end %>

          <% else %>

                  <% @post.post_comments.each do |post_comment| %>
                  <table>

                    <div class="show-coment">
                      <tr>
                      <th><%= attachment_image_tag post_comment.user, :user_image, :fill, 50, 50, format: 'jpeg', fallback: "/images/stylist_image.jpeg" , class: "stylist-image" %></th>
                
                                <td><%= post_comment.user.user_name %>
                                
                                <%= post_comment.created_at.strftime('%Y/%m/%d') %></td>
                            
                            
                                <td class="show-coment-dtail"><%= post_comment.comment %></td></tr>
                    </div>

                  </table>

                  <% end %>
                      
          <% end %>




                  



          


        </div>

                <% if current_stylist != nil %>
                    <% if current_stylist.id == @post.stylist.id %>



                    
                     <div class="row show-btn">
                             <%=link_to "EDIT", edit_post_path, class: "btn btn-primary btn-lg showb" %>
                             <%= link_to "DESTROY", post_path(@post), method: :delete, "data-confirm" => "本当に消しますか?", class: "btn btn-primary btn-lg" %>


                     </div>
                    <% end %>


                <% end %>
      
  
</div>