config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
devise_for :stylists, controllers: {
  sessions:      'stylists/sessions',
  passwords:     'stylists/passwords',
  registrations: 'stylists/registrations'
}
devise_for :users, controllers: {
  sessions:      'users/sessions',
  passwords:     'users/passwords',
  registrations: 'users/registrations'
}
root 'users#top'
get 'posts/rank', to: 'posts#rank'
get 'users/top', to: 'users#top'
resources :users 
resources :stylists do
	resources :follows, only: [:create, :destroy, :show]
  resources :salons, expect: [:index]
end
resources :posts do
    resource :favorites, only: [:create, :destroy]
    resource :post_comments, only: [:create, :destroy]
end
resources :messages, only: [:create]
resources :rooms, only: [:create, :show, :index]
resources :user_chats, only: [:show, :create]
resources :chat_messages, only: [:create]
resources :boards do
	resource :board_comments, only: [:create, :destroy]
end


end

app/models/board.rb
class Board < ApplicationRecord
	belongs_to :stylist
	has_many :board_comments, dependent: :destroy
	attachment :board_image


	validates :title, presence: true, length: { in: 1..30}
    validates :content, presence: true, length: { in: 1..200 }
    

end

app/models/board_comment.rb
class BoardComment < ApplicationRecord
	belongs_to :stylist
    belongs_to :board


    validates :comment, presence: true, length: { in: 1..500}
    
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
  belongs_to :user_chat

   validates :content, presence: true, length: { in: 1..200 }
  
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :stylist
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/follow.rb
class Follow < ApplicationRecord
	belongs_to :user
    belongs_to :stylist
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :stylist
  belongs_to :room

   validates :content, presence: true, length: { in: 1..200 }
    
end

app/models/post.rb
class Post < ApplicationRecord
	is_impressionable counter_cache: true
	attachment :post_image

    belongs_to :stylist
    has_many :favorites
    has_many :users, through: :favorites
    has_many :post_comments, dependent: :destroy


    enum category: { men: 0, short: 1, medium: 2, long: 3 }


    validates :post_name, presence: true, length: { in: 1..20 }
    validates :post_opinion, presence: true, length: { in: 1..100 }
    
    


    def favorited_by?(user)
          favorites.where(user_id: user.id).exists?
        end
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	 belongs_to :user
     belongs_to :post

      validates :comment, presence: true, length: { in: 1..200 }
    



end

app/models/room.rb
class Room < ApplicationRecord

  has_many :messages, dependent: :destroy
  has_many :entries
  has_many :stylists, through: :entries
  # accepts_nested_attributes_for :entries
end

app/models/salon.rb
class Salon < ApplicationRecord
	belongs_to :order
end

app/models/stylist.rb
class Stylist < ApplicationRecord

  is_impressionable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :boards, dependent: :destroy
  
  has_many :entries, dependent: :destroy
  has_many :rooms, through: :entries, dependent: :destroy

  has_many :user_chats, dependent: :destroy
  has_many :chat_messages, dependent: :destroy
  has_many :follows, dependent: :destroy
  has_many :user, through: :follows
  has_many :boards, dependent: :destroy
  has_many :board_comments, dependent: :destroy
  has_one :salon, dependent: :destroy

  attachment :stylist_image
  attachment :salon_image

  validates :stylist_name, presence: true, length: { in: 1..20 }
  validates :salon_name, presence: true, length: { in: 1..20 }
  validates :stylist_age, presence: true, length: { in: 1..20 }
  validates :email, presence: true, length: { in: 1..30 }
  validates :stylist_region,    length: { maximum: 20 }
  validates :stylist_hobby,    length: { maximum: 50 }
  validates :fort,    length: { maximum: 50 } 
  validates :stylist_introduction,    length: { maximum: 500 } 
  validates :phone_number,    length: { maximum: 15 } 
  validates :holiday,    length: { maximum: 30 } 
  validates :business_houre,    length: { maximum: 40 } 
  validates :menu,    length: { maximum: 500 } 
  validates :salon_introduction,    length: { maximum: 500 } 
  validates :salon_url,    length: { maximum: 100 } 










  

  enum stylist_sex: { man: 1, woman: 2 }

  def favorited_by?(user)
          follows.where(user_id: user.id).exists?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :user_chats, dependent: :destroy
  has_many :chat_messages, dependent: :destroy
  has_many :favorites
  has_many :posts, through: :favorites
  has_many :follows, dependent: :destroy
  has_many :stylists, through: :follows
  has_many :post_comments, dependent: :destroy


  attachment :user_image

  enum user_sex: { man: 1, woman: 2 }

  validates :user_name, presence: true, length: { in: 1..20 }
  validates :user_age, presence: true, length: { in: 1..20 }
  validates :email, presence: true, length: { in: 1..30 }
  validates :user_region,    length: { maximum: 20 }
  validates :user_hobby,    length: { maximum: 50 }
  validates :user_introduction,    length: { maximum: 500 }



end

app/models/user_chat.rb
class UserChat < ApplicationRecord
  belongs_to :stylist
  belongs_to :user
  has_many :chat_messages, dependent: :destroy
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/salons_helper.rb
module SalonsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Belle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <header>
      <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
      <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample7">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">
        belle
      </a>
      </div>
    
      <div class="collapse navbar-collapse" id="navbarEexample7">
      <ul class="nav navbar-nav">

                <% if stylist_signed_in? && current_stylist %>

                <li class="active">
                  <%= link_to "HOME", posts_path %>
                </li>
                <li class="active">
                  <%= link_to "RANK", posts_rank_path %>
                </li>
                <li class="active">
                  <%= link_to "STYLIST", stylists_path %>
                </li>
                <li class="active">
                  <%= link_to "BOARD", boards_path %>
                </li>
                <li class="active">
                  <%= link_to "MYPAGE", stylist_path(current_stylist) %>
                </li>

                <li class="active">
                  <%= link_to "LOGOUT", destroy_stylist_session_path, method: :delete%>
                </li>
               


                <% elsif user_signed_in? %>


                <li class="active">
                  <%= link_to "HOME", posts_path %>
                </li>
                <li class="active">
                  <%= link_to "RANK", posts_rank_path %>
                </li>
                <li class="active">
                  <%= link_to "STYLIST", stylists_path %>
                </li>
                <li class="active">
                  <%= link_to "MYPAGE", user_path(current_user) %>
                </li>
                <li class="active">
                   <%= link_to "LOG OUT" , destroy_user_session_path, method: :delete %>
                </li>
                
                
                <% else %>

                <li class="active">
                 <%= link_to "HOME", root_path %>
                </li>

                <li class="active sign_button2 sign_up_button2">
                 <a>STYLISTLOGIN</a>
                </li>

                <li class="active sign_button2 sign_in_button2">
                 <a>USERLOGIN</a>
                </li>
                
                <% end %>
        
        </ul>
      
        </div>
        </div>
        </nav>
                 

      
      
    </header>
    <%= yield %>
  </body>
</html>